"""Spec remove

Revision ID: 1ca488b570de
Revises: d6f71ea79fc5
Create Date: 2020-10-09 09:31:18.979664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca488b570de'
down_revision = 'd6f71ea79fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_specials_pname', table_name='specials')
    op.drop_table('specials')
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_table('specials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('pname', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=140), nullable=True),
    sa.Column('prize', sa.FLOAT(), nullable=True),
    sa.Column('availabilty', sa.BOOLEAN(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=150), nullable=True),
    sa.Column('store_id', sa.INTEGER(), nullable=True),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('availabilty IN (0, 1)'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['retail_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_specials_pname', 'specials', ['pname'], unique=False)
    # ### end Alembic commands ###
