"""order_item table update

Revision ID: 205dd2c0d8c6
Revises: 9ab2577b296e
Create Date: 2020-09-13 17:20:15.810909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205dd2c0d8c6'
down_revision = '9ab2577b296e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('customer', sa.Integer(), nullable=True))
    op.add_column('order_item', sa.Column('ordered', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'user', ['customer'], ['id'])
    op.drop_column('order_item', 'purchase_date')
    op.create_foreign_key(None, 'product', 'retail_stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'item')
    op.drop_column('product', 'date')
    op.drop_index('ix_retail_stores_store_name', table_name='retail_stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retail_stores_store_name', 'retail_stores', ['store_name'], unique=False)
    op.add_column('product', sa.Column('date', sa.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('item', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.add_column('order_item', sa.Column('purchase_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'ordered')
    op.drop_column('order_item', 'customer')
    # ### end Alembic commands ###
