"""update on error on model

Revision ID: 38a64fdcfd29
Revises: 7bc8ffcbf2b3
Create Date: 2020-09-10 13:03:54.218293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a64fdcfd29'
down_revision = '7bc8ffcbf2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_details', sa.Column('ship_add', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.create_foreign_key(None, 'product', 'retail_stores', ['store_id'], ['id'])
    op.drop_column('product', 'date')
    op.drop_column('product', 'item')
    op.drop_index('ix_retail_stores_store_name', table_name='retail_stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retail_stores_store_name', 'retail_stores', ['store_name'], unique=False)
    op.add_column('product', sa.Column('item', sa.VARCHAR(length=64), nullable=True))
    op.add_column('product', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('customer_order_details', 'ship_add')
    # ### end Alembic commands ###
