"""user admin

Revision ID: 4ea1f554e1a1
Revises: 1ca488b570de
Create Date: 2020-10-09 09:34:48.949278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea1f554e1a1'
down_revision = '1ca488b570de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order_details', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('customer_order_details', 'is_admin')
    # ### end Alembic commands ###
