"""aisle update 3

Revision ID: 60e3cbc90edc
Revises: 6aba436f3a7e
Create Date: 2020-10-06 12:15:55.343900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e3cbc90edc'
down_revision = '6aba436f3a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.add_column('product', sa.Column('aisle_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'aisles', ['aisle_id'], ['id'])
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'aisle_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
