"""access_token

Revision ID: 6dfd3647356b
Revises: d9fdb44a6ddb
Create Date: 2020-10-14 14:08:13.819166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfd3647356b'
down_revision = 'd9fdb44a6ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    op.add_column('user', sa.Column('access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token')
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
