"""ilse update

Revision ID: 72015a554b93
Revises: 988b1db77c17
Create Date: 2020-10-06 12:29:40.348701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72015a554b93'
down_revision = '988b1db77c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.add_column('product', sa.Column('aisl_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product', 'aisles', ['aisl_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'aisl_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
