"""update on order details table

Revision ID: 7bc8ffcbf2b3
Revises: afdd038c7ff5
Create Date: 2020-09-10 13:02:01.418378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc8ffcbf2b3'
down_revision = 'afdd038c7ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'product', 'retail_stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'item')
    op.drop_column('product', 'date')
    op.drop_index('ix_retail_stores_store_name', table_name='retail_stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retail_stores_store_name', 'retail_stores', ['store_name'], unique=False)
    op.add_column('product', sa.Column('date', sa.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('item', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    # ### end Alembic commands ###
