"""product table update

Revision ID: 91bf077aa15c
Revises: 614fbd53b919
Create Date: 2020-09-30 18:45:41.327597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bf077aa15c'
down_revision = '614fbd53b919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_a_name', table_name='admin')
    op.drop_index('ix_admin_id', table_name='admin')
    op.drop_table('admin')
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_column('product', 'category_id')
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('a_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('a_last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_h', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_id', 'admin', ['id'], unique=False)
    op.create_index('ix_admin_a_name', 'admin', ['a_name'], unique=False)
    # ### end Alembic commands ###
