"""Specials db add 2

Revision ID: bd10d8ec452d
Revises: 3729dee877d8
Create Date: 2020-10-09 08:57:42.862064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd10d8ec452d'
down_revision = '3729dee877d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aisles', 'image')
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.add_column('order_item', sa.Column('special_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'specials', ['special_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'special_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.add_column('aisles', sa.Column('image', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
