"""Specials db add 3

Revision ID: d6f71ea79fc5
Revises: 6a791832b6a4
Create Date: 2020-10-09 09:12:22.885187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f71ea79fc5'
down_revision = '6a791832b6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order', 'customer_order_details', ['billing_address'], ['id'])
    op.add_column('order_item', sa.Column('special_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_item', 'specials', ['special_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_column('order_item', 'special_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    # ### end Alembic commands ###
