"""orders table update

Revision ID: dee7dabf96f0
Revises: 205dd2c0d8c6
Create Date: 2020-09-13 17:49:47.005058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee7dabf96f0'
down_revision = '205dd2c0d8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('OrderItem', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'order_item', ['OrderItem'], ['id'])
    op.create_foreign_key(None, 'order_item', 'user', ['customer'], ['id'])
    op.drop_column('order_item', 'purchase_date')
    op.create_foreign_key(None, 'product', 'category', ['category'], ['id'])
    op.create_foreign_key(None, 'product', 'retail_stores', ['store_id'], ['id'])
    op.drop_column('product', 'item')
    op.drop_column('product', 'date')
    op.drop_index('ix_retail_stores_store_name', table_name='retail_stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_retail_stores_store_name', 'retail_stores', ['store_name'], unique=False)
    op.add_column('product', sa.Column('date', sa.DATETIME(), nullable=True))
    op.add_column('product', sa.Column('item', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.add_column('order_item', sa.Column('purchase_date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'OrderItem')
    # ### end Alembic commands ###
